### ISSUE TITLE
il metodo registrazione non si avvia sul server 

### ISSUE THREAD

**Issue by francescolillo24** [marcobonaccorso/kezapp-mac#3]
abbiamo provato ad avviare testare l aplicazione  sia da lato client che da lato server ma non risponde sotto le mando il codice

@Override
    public RegistrazioneDto registrazione(RichiediRegistrazioneDto reqDto) {
        //creare una chat con i dati ricevuti dal controller
        Chat c1 = new Chat(reqDto.getNickname());
        //salvarla su db e recuperarne il valore con l'id aggiornato
        c1 = chatRepository.save(c1);
        //convertire l'id in stringa e metterlo nella sessione
        String s2 = c1.getId().toString();
        c1.setSessione(s2);
        //aggiornare sul db la chat
        c1 = chatRepository.save(c1);
        //ritornare il dto richiesto dal controller
        RegistrazioneDto reg = new RegistrazioneDto();
        // impostare nel dto la lista contatti,messaggi e sessione
        RegistrazioneDto regDto = new RegistrazioneDto();
        regDto.setListaContatti(recuperaTutteChat());
        regDto.setListaMessaggi(recuperaTuttiMessaggi());
        // ritornare questo dto cosi compilato
        return reg;
    }

questo e il controller 

 @RequestMapping("/registrazione")
    public RegistrazioneDto registrazione(RichiediRegistrazioneDto reqDto) {
        return registrazione(reqDto);
    }

io penso che il return del controller debba essere uguale a quello del serviceimpl

**Comment by luca-lezzerini** [comment]
Manca la console e lo strumento network

**Comment by luca-lezzerini** [comment]
Ma non avevamo già risolto in aula questa cosa?
